from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver=webdriver.ChromiumEdge()
driver.get("https://typekadeh.com")
btn=driver.find_element(By.CLASS_NAME,"tk-btn")
btn.click()
time.sleep(4)
btn=driver.find_elements(By.CLASS_NAME,"iranYekan-14--bold")
btn=btn[0]
btn.click()
time.sleep(1)
input=driver.find_elements(By.CLASS_NAME,"tk-input__dense")
time.sleep(1)
input[1].send_keys("your email")
time.sleep(1)
input[2].send_keys("....")
time.sleep(1)
btn=driver.find_elements(By.CLASS_NAME,"tk-btn--primary")
btn[3].click()
time.sleep(1)
btn=driver.find_element(By.CLASS_NAME,"space-x-reverse")
btn.click()
time.sleep(4)
input=driver.find_element(By.CLASS_NAME,"tk-input__dense")
input.send_keys("....")
btn=driver.find_elements(By.CLASS_NAME,"tk-btn--radius")
print(len(btn))
btn[2].click()
time.sleep(2)
btn=driver.find_elements(By.CLASS_NAME,"vertical-center")
print(len(btn))
btn[2].click()
time.sleep(20)
